version: '2.2'

services:
  cube_api:
    restart: always
    platform: linux/x86_64
    image: cubejs/cube:v0.31.57
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_DB_HOST=cube_mysql
      - CUBEJS_DB_NAME=cube_db
      - CUBEJS_DB_USER=root
      - CUBEJS_DB_PASS=root

      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=secret
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_worker_1
      - cubestore_worker_2
      - cube_refresh_worker
      - redis
    networks:
      - cube
    links:
      - cube_mysql

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.31.57
    environment:
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_DB_HOST=cube_mysql
      - CUBEJS_DB_NAME=cube_db
      - CUBEJS_DB_USER=root
      - CUBEJS_DB_PASS=root

      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_REDIS_URL=redis://redis:6379
      - CUBEJS_API_SECRET=secret
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - .:/cube/conf
    networks:
      - cube
    links:
      - cube_mysql

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.31.57
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    networks:
      - cube

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.31.57
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router
    networks:
      - cube

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.31.57
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router
    networks:
      - cube

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
    networks:
      - cube

  cube_mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: cube_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'cube_db'   
      MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      - cube

networks:
  cube:
    driver: bridge