name: Test SSH to EC2

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 and run uptime
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH successful!"
            uptime

